version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies
    ports:
      - "8080:8080"    
    networks:
      node_net:
        ipv4_address: 172.28.1.5
      
  # redis:
  #   image: "redis:alpine"

  #   command: redis-server --requirepass secret

  #   ports:
  #     - "6379:6379"

  #   # volumes:
  #   #   - $PWD/redis-data:/var/lib/redis
  #   #   - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  #   environment:
  #     - REDIS_REPLICATION_MODE=master

  #   networks:
  #     node_net:
  #       ipv4_address: 172.28.1.4
    
# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16